apiVersion: v1
kind: Service
metadata:
  name: gremlin-instana-api
spec:
  selector:
      app.kubernetes.io/name: instana-agent
  ports:
    - protocol: TCP
      port: 42699
      targetPort: 42699
---
apiVersion: v1
kind: Service
metadata:
 name: gremlin-instana-proxy
spec:
 selector:
   role: gremlin-instana-proxy
 ports:
   - name: port443
     protocol: TCP
     port: 443
     targetPort: 443
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: gremlin-instana-proxy
 labels:
   role: gremlin-instana-proxy
spec:
 replicas: 1
 selector:
   matchLabels:
     role: gremlin-instana-proxy
 template:
   metadata:
     labels:
       role: gremlin-instana-proxy
   spec:
     containers:
     - name: gremlin-instana-proxy
       image: "nginx"
       volumeMounts:
       - name: certs
         mountPath: /etc/nginx/certs/
         readOnly: true
       - name: credentials
         mountPath: /etc/nginx-auth/
         readOnly: true
       - name: nginx-config
         mountPath: /etc/nginx/conf.d/
     volumes:
     - name: certs
       secret:
         secretName: gremlin-instana-proxy-certs
     - name: credentials
       secret:
         secretName: gremlin-instana-proxy-credentials
     - name: nginx-config
       configMap:
         name: gremlin-instana-proxy-config
